from providers import Provider
from sports import Sport
from channel import Channel
from channel_sub_cat import ChannelSubCat


EVENT_ID = "33254789"
EVENT_NAME = "Test genius event"

VIDEO_ITEM_ID = 177605698
PROVIDER_ID = Provider.GENIUS.value
PROVIDER_EVENT_ID = 20000146689
SPORT_ID = Sport.AMERICAN_FOOTBALL.value
CHANNEL_ID = Channel.WEB.value
CHANNEL_SUB_CAT_ID = ChannelSubCat.WEB.value


def show_select_queries():
    QUERY_TBL_SPORT_EVENT = f"""
SELECT * FROM DATA_VIDEO.TBL_SPORT_EVENT
	WHERE EVENT_ID = {EVENT_ID};
"""

    print(QUERY_TBL_SPORT_EVENT)
    
    QUERY_TBL_SCHEDULE_ITEM = f"""
SELECT * FROM DATA_VIDEO.TBL_SCHEDULE_ITEM
	WHERE VIDEO_ITEM_ID = {VIDEO_ITEM_ID};
"""

    print(QUERY_TBL_SCHEDULE_ITEM)

    QUERY_TBL_MAPPED_ENTITIES = f"""
SELECT * FROM TBL_MAPPED_ENTITIES
    WHERE VIDEO_ITEM_ID = {VIDEO_ITEM_ID};
"""

    print(QUERY_TBL_MAPPED_ENTITIES)
    
    QUERY_TBL_STREAM_STATE = f"""
SELECT * FROM TBL_STREAM_STATE
    WHERE VIDEO_ITEM_ID = {VIDEO_ITEM_ID};
"""

    print(QUERY_TBL_STREAM_STATE)


def show_insert_queries():    
    QUERY_TBL_SPORT_EVENT = f"""
INSERT INTO DATA_VIDEO.TBL_SPORT_EVENT
(EVENT_ID,NAME,EVENT_TYPE_ID,VENUE,OPEN_DATE,COMPETITION_NAME,DATA_FOR_MAPPING_UPDATED_AT,IN_PLAY) VALUES
    ({EVENT_ID}, '{EVENT_NAME}', 1, null, CURRENT_TIMESTAMP - INTERVAL '1' HOUR, '{EVENT_NAME}', CURRENT_TIMESTAMP, 'Y');
    """
    
    print(QUERY_TBL_SPORT_EVENT)

    QUERY_TBL_SCHEDULE_ITEM = f"""
INSERT INTO TBL_SCHEDULE_ITEM
(VIDEO_ITEM_ID, PROVIDER_ID, PROVIDER_EVENT_ID, PROVIDER_EVENT_NAME, PROVIDER_SPORTS_TYPE, PROVIDER_STARTTIME_GMT, PROVIDER_ENDTIME_GMT, PROVIDER_COMPETITION,
 PROVIDER_VENUE, PROVIDER_COUNTRY, PROVIDER_LANGUAGES, PROVIDER_CHARGEABLE_FLAG, PROVIDER_BLOCKED_COUNTRIES, PROVIDER_STREAMING_URL, OVERRIDE_EVENT_NAME,
 OVERRIDE_STARTTIME_GMT, OVERRIDE_ENDTIME_GMT, OVERRIDE_COMPETITION, OVERRIDE_VENUE, OVERRIDE_COUNTRY, OVERRIDE_BLOCKED_COUNTRIES, BETFAIR_SPORTS_ID,
 LEAD_TIME_SEC, TRAIL_TIME_SEC, CHANNEL_ID, CHANNEL_SUB_CAT_ID, IMPORT_STATUS_ID, APPROVAL_STATUS_ID, REVIEW_STATUS_YN, MODIFIED_BY_SYSTEM_ID, MODIFIED_BY_USER,
 MODIFIED_DATE, MODIFIED_BY_IP, STREAM_TYPE_ID, CREATED_DATE, PROVIDER_FINISHED, EXTRACTED_FROM_MULTI_MATCH, BRAND_ID)
VALUES
    ({VIDEO_ITEM_ID}, {PROVIDER_ID}, '{PROVIDER_EVENT_ID}', '{EVENT_NAME}', '{SPORT_ID}', CURRENT_TIMESTAMP - INTERVAL '1' HOUR, null, 'NFL',
     null, null, null, null, null, null, null,
     CURRENT_TIMESTAMP - INTERVAL '1' HOUR, null, null, null, null, null, 1,
     300, 0, {CHANNEL_ID}, {CHANNEL_SUB_CAT_ID}, 'N', 'A', 'N', 1, 'ie1-vhs01a-nxt.nxt.betfair',
     CURRENT_TIMESTAMP, '10.204.152.17', 2, CURRENT_TIMESTAMP, null, null, 3);
"""

    print(QUERY_TBL_SCHEDULE_ITEM)

    QUERY_TBL_MAPPED_ENTITES = f"""
INSERT INTO TBL_MAPPED_ENTITIES
(VIDEO_ITEM_ID, MAPPING_PROVIDER_ID, MAPPING_PRIMARY_ID, MAPPING_SECONDARY_ID, MAPPING_DESCRIPTION, MAPPING_STATUS_ID, APPROVAL_STATUS_ID, MODIFIED_BY_SYSTEM_ID, MODIFIED_BY_USER,
 MODIFIED_DATE, MATCHING_TYPE_ID, FACET_START_TIME)
VALUES
    ({VIDEO_ITEM_ID}, {PROVIDER_ID}, {PROVIDER_EVENT_ID}, 'EVENT:{PROVIDER_EVENT_ID}', '{EVENT_NAME}', 'N','A', 2, 'ie2-vhs01b-nxt.nxt.betfair', CURRENT_TIMESTAMP, 'I', CURRENT_TIMESTAMP + INTERVAL '1' HOUR);
"""

    print(QUERY_TBL_MAPPED_ENTITES)

    QUERY_TBL_STREAM_STATE = f"""
    INSERT INTO TBL_STREAM_STATE
    (VIDEO_ITEM_ID, STREAM_STATE, FACET_STATE)
    VALUES
        ({VIDEO_ITEM_ID},'STREAM','OPEN');
    """

    print(QUERY_TBL_STREAM_STATE)


def show_update_queries():
    QUERY_TBL_SPORT_EVENT = f"""
UPDATE DATA_VIDEO.TBL_SPORT_EVENT
    SET OPEN_DATE = CURRENT_TIMESTAMP - INTERVAL '1' HOUR
	WHERE EVENT_ID = {EVENT_ID};
"""

    print(QUERY_TBL_SPORT_EVENT)
    
    QUERY_TBL_SCHEDULE_ITEM = f"""
UPDATE DATA_VIDEO.TBL_SCHEDULE_ITEM
SET PROVIDER_ID = {PROVIDER_ID},
    PROVIDER_EVENT_ID = {PROVIDER_EVENT_ID},
    PROVIDER_EVENT_NAME = '{EVENT_NAME}',
    PROVIDER_SPORTS_TYPE = {SPORT_ID},
    PROVIDER_STARTTIME_GMT = CURRENT_TIMESTAMP,
    PROVIDER_ENDTIME_GMT = NULL,
    OVERRIDE_STARTTIME_GMT = CURRENT_TIMESTAMP,
    OVERRIDE_ENDTIME_GMT  = NULL
WHERE VIDEO_ITEM_ID = {VIDEO_ITEM_ID};
"""

    print(QUERY_TBL_SCHEDULE_ITEM)


def main():
    show_select_queries()
    # show_insert_queries()
    # show_update_queries()


if __name__ == "__main__":
    main()