------------------ TBL_SPORT_EVENT ------------------

SELECT * FROM DATA_VIDEO.TBL_SPORT_EVENT
    WHERE EVENT_ID = <EVENT_ID>
;

INSERT INTO DATA_VIDEO.TBL_SPORT_EVENT
(EVENT_ID,NAME,EVENT_TYPE_ID,VENUE,OPEN_DATE,COMPETITION_NAME,DATA_FOR_MAPPING_UPDATED_AT,IN_PLAY) VALUES
    (<EVENT_ID>, '<EVENT_NAME>', 1, null, CURRENT_TIMESTAMP - INTERVAL '1' HOUR, '<EVENT_NAME>', CURRENT_TIMESTAMP, 'Y')
;

UPDATE DATA_VIDEO.TBL_SPORT_EVENT
    SET OPEN_DATE = CURRENT_TIMESTAMP - INTERVAL '1' HOUR
        WHERE EVENT_ID = <EVENT_ID>
;

------------------ TBL_SCHEDULE_ITEM ------------------

SELECT * FROM DATA_VIDEO.TBL_SCHEDULE_ITEM
        WHERE VIDEO_ITEM_ID = <VIDEO_ITEM_ID>
;

INSERT INTO TBL_SCHEDULE_ITEM
(VIDEO_ITEM_ID, PROVIDER_ID, PROVIDER_EVENT_ID, PROVIDER_EVENT_NAME, PROVIDER_SPORTS_TYPE, PROVIDER_STARTTIME_GMT, PROVIDER_ENDTIME_GMT, PROVIDER_COMPETITION,
 PROVIDER_VENUE, PROVIDER_COUNTRY, PROVIDER_LANGUAGES, PROVIDER_CHARGEABLE_FLAG, PROVIDER_BLOCKED_COUNTRIES, PROVIDER_STREAMING_URL, OVERRIDE_EVENT_NAME,
 OVERRIDE_STARTTIME_GMT, OVERRIDE_ENDTIME_GMT, OVERRIDE_COMPETITION, OVERRIDE_VENUE, OVERRIDE_COUNTRY, OVERRIDE_BLOCKED_COUNTRIES, BETFAIR_SPORTS_ID,
 LEAD_TIME_SEC, TRAIL_TIME_SEC, CHANNEL_ID, CHANNEL_SUB_CAT_ID, IMPORT_STATUS_ID, APPROVAL_STATUS_ID, REVIEW_STATUS_YN, MODIFIED_BY_SYSTEM_ID, MODIFIED_BY_USER,
 MODIFIED_DATE, MODIFIED_BY_IP, STREAM_TYPE_ID, CREATED_DATE, PROVIDER_FINISHED, EXTRACTED_FROM_MULTI_MATCH, BRAND_ID)
VALUES
    (<VIDEO_ITEM_ID>, <PROVIDER_ID>, '<PROVIDER_EVENT_ID>', '<EVENT_NAME>', '<SPORT_ID>', CURRENT_TIMESTAMP - INTERVAL '1' HOUR, null, 'NFL',
     null, null, null, null, null, null, null,
     CURRENT_TIMESTAMP - INTERVAL '1' HOUR, null, null, null, null, null, 1,
     300, 0, <CHANNEL_ID>, <CHANNEL_SUB_CAT_ID>, 'N', 'A', 'N', 1, 'ie1-vhs01a-nxt.nxt.betfair',
     CURRENT_TIMESTAMP, '10.204.152.17', 2, CURRENT_TIMESTAMP, null, null, 3)
;

UPDATE DATA_VIDEO.TBL_SCHEDULE_ITEM
SET PROVIDER_ID = <PROVIDER_ID>,
    PROVIDER_EVENT_ID = <PROVIDER_EVENT_ID>,
    PROVIDER_EVENT_NAME = '<EVENT_NAME>',
    PROVIDER_SPORTS_TYPE = <SPORT_ID>,
    PROVIDER_STARTTIME_GMT = CURRENT_TIMESTAMP - INTERVAL '1' HOUR,
    PROVIDER_ENDTIME_GMT = NULL,
    OVERRIDE_STARTTIME_GMT = CURRENT_TIMESTAMP - INTERVAL '1' HOUR,
    OVERRIDE_ENDTIME_GMT  = NULL
WHERE VIDEO_ITEM_ID = <VIDEO_ITEM_ID>
;

------------------ TBL_MAPPED_ENTITIES ------------------


SELECT * FROM TBL_MAPPED_ENTITIES
    WHERE VIDEO_ITEM_ID = <VIDEO_ITEM_ID>
;


INSERT INTO TBL_MAPPED_ENTITIES
(VIDEO_ITEM_ID, MAPPING_PROVIDER_ID, MAPPING_PRIMARY_ID, MAPPING_SECONDARY_ID, MAPPING_DESCRIPTION, MAPPING_STATUS_ID, APPROVAL_STATUS_ID, MODIFIED_BY_SYSTEM_ID, MODIFIED_BY_USER,
 MODIFIED_DATE, MATCHING_TYPE_ID, FACET_START_TIME)
VALUES
    (<VIDEO_ITEM_ID>, <PROVIDER_ID>, <PROVIDER_EVENT_ID>, 'EVENT:<PROVIDER_EVENT_ID>', '<EVENT_NAME>', 'N','A', 2, 'ie2-vhs01b-nxt.nxt.betfair', CURRENT_TIMESTAMP, 'I', CURRENT_TIMESTAMP + INTERVAL '1' HOUR)
;

UPDATE DATA_VIDEO.TBL_MAPPED_ENTITIES
SET MAPPING_PROVIDER_ID = <PROVIDER_ID>,
    MAPPING_PRIMARY_ID = <EVENT_ID>,
    MAPPING_SECONDARY_ID = 'EVENT:<EVENT_ID>',
    MAPPING_DESCRIPTION = '<EVENT_NAME>',
    MAPPING_STATUS_ID = 'N',
    APPROVAL_STATUS_ID = 'A',
    FACET_START_TIME = CURRENT_TIMESTAMP - INTERVAL '1' HOUR
WHERE VIDEO_ITEM_ID = <VIDEO_ITEM_ID>
;

------------------ TBL_STREAM_STATE ------------------


SELECT * FROM TBL_STREAM_STATE
    WHERE VIDEO_ITEM_ID = <VIDEO_ITEM_ID>
;

INSERT INTO TBL_STREAM_STATE
(VIDEO_ITEM_ID, STREAM_STATE, FACET_STATE)
VALUES
    (<VIDEO_ITEM_ID>,'STREAM','OPEN')
;

------------------ TBL_TYPE_SPORTS ------------------

SELECT * FROM TBL_TYPE_SPORTS;

-- AMERICAN_FOOTBALL=6423
-- GOLF=3

------------------ TBL_TYPE_PROVIDER ------------------

SELECT * FROM TBL_TYPE_PROVIDER

-- IMG_GOLF=36
-- GENIUS=40
